version: '3'

services:
   db:
     image: mysql:5.7
     platform: linux/amd64
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: vincecater0911
       MYSQL_DATABASE: wordpress
       MYSQL_USER: kameiRyosuke
       MYSQL_PASSWORD: vincecater0911

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "81:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: kameiRyosuke
       WORDPRESS_DB_PASSWORD: vincecater0911
volumes:
    db_data:
